config/routes.rb
Rails.application.routes.draw do
  resources :dispatches do 
  	resources :comments
  end
  devise_for :users
  root 'dispatches#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :dispatch, required: true, inverse_of: :comments
end

app/models/dispatch.rb
class Dispatch < ApplicationRecord
	belongs_to :user, required: true
	has_many :comments, dependent: :destroy, inverse_of: :dispatch

	accepts_nested_attributes_for :comments #, reject_if: proc { |attributes| attributes[:body].blank? }, allow_destroy: true

	self.per_page = 10
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dispatches
  has_many :comments 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @dispatch = Dispatch.find(params[:dispatch_id])
    @comment = @dispatch.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @dispatch = Dispatch.find(params[:dispatch_id])
    @comment = @dispatch.comments.build(comment_params)
    # @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    # @comment.save

    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      # params.fetch(:comment, {})
      params.require(:comment).permit(:body, :dispatch_id, :user_id)
    end
end

app/controllers/dispatches_controller.rb
class DispatchesController < ApplicationController
  before_action :set_dispatch, only: [:show, :edit, :update, :destroy]

  # GET /dispatches
  # GET /dispatches.json
  def index
    @dispatches = Dispatch.paginate(:page => params[:page]).order('updated_at DESC')
  end

  # GET /dispatches/1
  # GET /dispatches/1.json
  def show
    @comments = @dispatch.comments.all 
  end

  # GET /dispatches/new
  def new
    @dispatch = Dispatch.new
    @comment = @dispatch.comments.build
  end

  # GET /dispatches/1/edit
  def edit
  end

  # POST /dispatches
  # POST /dispatches.json
  def create
    @dispatch = Dispatch.new(dispatch_params)
    @dispatch.user_id = current_user.id
    respond_to do |format|
      if @dispatch.save
        format.html { redirect_to @dispatch, notice: 'Dispatch was successfully created.' }
        format.json { render :show, status: :created, location: @dispatch }
      else
        format.html { render :new }
        format.json { render json: @dispatch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dispatches/1
  # PATCH/PUT /dispatches/1.json
  def update
    respond_to do |format|
      if @dispatch.update(dispatch_params)
        format.html { redirect_to @dispatch, notice: 'Dispatch was successfully updated.' }
        format.json { render :show, status: :ok, location: @dispatch }
      else
        format.html { render :edit }
        format.json { render json: @dispatch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dispatches/1
  # DELETE /dispatches/1.json
  def destroy
    @dispatch.destroy
    respond_to do |format|
      format.html { redirect_to dispatches_url, notice: 'Dispatch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_comment
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.dispatch_id = 12
    @comment.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dispatch
      @dispatch = Dispatch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dispatch_params
      params.require(:dispatch).permit(:dps_number, :status, :user_id, :channel, comments_attributes: [:id, :body, :dispatch_id, :user_id])
    end

    def comment_params
      params.require(:comment).permit(:body, :dispatch_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dispatches_helper.rb
module DispatchesHelper
end

app/views/comments/_form.html.erb
<%= form_for([@dispatch, @comment]) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%#= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/dispatches/_form.html.erb
<%= form_for(dispatch) do |f| %>
  <% if dispatch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dispatch.errors.count, "error") %> prohibited this dispatch from being saved:</h2>

      <ul>
      <% dispatch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dps_number %>
    <%= f.text_area :dps_number %>
  </div>

  <div class="field">
    <%= f.label :channel %>
    <%= f.select :channel, [['Email','Email'],['Phone','Phone'],['Moxie','Moxie'],['DCCMT','DCCMT']] %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, [['Open','Open'],['Problem','Problem'],['Approved','Approved'],['Work in Progress','Work in Progress'],['DSP Assignment Failure','DSP Assignment Failure'],['No Service ETA','No Service ETA'],['No Part ETA','No Part ETA'],['Backlog','Backlog'],['Tech Not Onsite','Tech Not Onsite'],['Customer Deferred','Customer Deferred'],['Customer Unable to Set ETA','Customer Unable to Set ETA'],['Cancelled','Cancelled'],['Closed','Closed'],['Service Complete','Service Complete']] %>
  </div>

  <div class="field">
    <%= f.fields_for :comments do |comment_form| %>
      <%= comment_form.label "Comment" %>
      <%= comment_form.text_field :body %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dispatches/edit.html.erb
<h1>Editing Dispatch</h1>

<%= render 'form', dispatch: @dispatch %>

<%= link_to 'Show', @dispatch %> |
<%= link_to 'Back', dispatches_path %>

app/views/dispatches/index.html.erb
<p id="notice"><%= notice %></p>
<section>
      <div class="row">
        <div class="col-md-3">
          <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="fa fa-heart"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Service Complete</span>
              <span class="info-box-number">1,410</span>
            </div>
            <!-- /.info-box-content -->
          </div>
        </div>

        <div class="col-md-3">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-bug"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Open</span>
              <span class="info-box-number">1,410</span>
            </div>
            <!-- /.info-box-content -->
          </div>
        </div>

        <div class="col-md-3">
          <div class="info-box">
            <span class="info-box-icon bg-yellow"><i class="fa fa-bell-o"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Work in Progress</span>
              <span class="info-box-number">1,410</span>
            </div>
            <!-- /.info-box-content -->
          </div>
        </div>

        <div class="col-md-3">
          <div class="info-box">
            <span class="info-box-icon bg-red"><i class="fa fa-thumbs-down"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Problem</span>
              <span class="info-box-number">93,139</span>
            </div>
            <!-- /.info-box-content -->
          </div>
        </div>
      </div>
    </section>
<div class="box">
  <div class="box-header">
    <h3 class="box-title">All dispatches</h3>
    <div class="box-tools">
      <div class="input-group input-group-sm" style="width: 150px;">
        <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
        <div class="input-group-btn">
          <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
          
        </div>
      </div>
    </div>
  </div>
  <!-- /.box-header -->
  <div class="box-body table-responsive">
    <table class="table table-hover">
      <tbody>
        <tr>
          <th>ID</th>
          <th>DPS Number</th>
          <th>Channel</th>
          <th>Status</th>
          <th>Time Updated</th>
          <th>Action</th>
        </tr>
        <% @dispatches.each do |dispatch| %>
        <tr>
          <td><%= dispatch.id %></td>
          <td><%= dispatch.dps_number %></td>
          <td><%= dispatch.channel %></td>
          <td>
            <% if dispatch.status == "Service Complete" || dispatch.status == "Closed"  %>
              <span class="label label-success">
            <% elsif dispatch.status == "Work in Progress" || dispatch.status == "Customer Deferred" || dispatch.status == "Cancelled" %>
              <span class="label label-warning">
            <% else %>
              <span class="label label-danger">
            <% end %>
            <%= dispatch.status %></span>
          </td>
          <td><%= dispatch.updated_at.strftime('%b %e, %r') %></td>
          <td>
            <span>
              <%= link_to 'Show', dispatch %>
              <%= link_to 'Add comment', new_dispatch_comment_path(dispatch_id: dispatch.id) %>
              <%= link_to 'Edit', edit_dispatch_path(dispatch) %>
              <%= link_to 'Destroy', dispatch, method: :delete, data: { confirm: 'Are you sure?' } %>
            </span>
          </td>
        </tr>
        <% end %>
                
      </tbody>
    </table>
  </div>
  <div class="box-footer clearfix"  style="text-align: center;">
    <%= will_paginate @posts %>
  </div>
</div>

<%= link_to 'New Dispatch', new_dispatch_path %>
<a href="/dispatches/new"><button class="btn btn-info" style="margin-left: 30px;"><i class="fa fa-plus"></i> New Dispatch</button></a>

app/views/dispatches/new.html.erb
<h1>New Dispatch</h1>

<%= render 'form', dispatch: @dispatch %>

<%= link_to 'Back', dispatches_path %>

app/views/dispatches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dps number:</strong>
  <%= @dispatch.dps_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @dispatch.status %>
</p>

<% @comments.each do |comment| %>
	<p><%= comment.body %></p>
<% end %>

<%= link_to 'Edit', edit_dispatch_path(@dispatch) %> |
<%= link_to 'Back', dispatches_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dps Tracker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-check"></i> Alert!</h4>
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
        <%= alert %>
      </div>
    <% end %>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">DPS tracker</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="/dispatches/new">New Dispatch</a></li>
            <li><a href="#about">Follow ups</a></li>
            <li><a href="#contact">Boring Analytical Stuff</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>
  	<!-- <div class="new-dispatch">
      <a href="/dispatches/new"><i class="fa fa-plus-circle fa-5x"></i></a>
    </div> -->
    
    <%= yield %>
  </body>
</html>